import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/working">
          working page (schema exported from separate file)
        </Link>
      </div>
      <div>
        <Link href="/broken">broken page (schema exported from same file)</Link>
      </div>
    </>
  );
};

export default Home;
